const theme = {
  mainColor: "#2e2f32",
  subColor: "#C4C4C4",
  recordBgColor: "#f5f5f5",
  recordBoxOneCol: "735px",
  recordMobileH: "767px",
  recordMobileV: "480px",
  kdaFontDefault: "0.9rem",
  kdaFontMedium: "0.9rem",
  kdaFontSmall: "0.8rem",
  fontColor: "yellow",
  fontColorForLoginPageAndSignupPage: "white",
  placeholderColor: "#5883ab",
  MypageLineColor: "#e9edef",
  MypageFontColor: "#52595f",
  MypageSubColor: "#98a0a7",
  MypageButtonColor: "rgb(30, 161, 247)",
  MypageSmallHeader: "#7b858e",
  inputBorderColor: "white",
  titleLetterSpace: "12px",
  ChattingBackgroundColor: "#5383e8",
  ChattingLineColor: "#DCDCE0",
  ChattingRoomSentMessageColor: "#ffeb33",
};

export default theme;
